
export const plantVarieties: Record<string, string[]> = {
  'Mango': ['Alphonso', 'Banganapalli', 'Dasheri', 'Langra', 'Kesar', 'Totapuri', 'Neelam', 'Malgova', 'Chausa', 'Himsagar', 'Imam Pasand', 'Raspuri'],
  'Rice': ['Basmati', 'Sona Masuri', 'Ponni', 'Jeera Samba', 'Matta Rice', 'Ambemohar', 'Gobindobhog', 'Kala Namak', 'IR-64', 'Swarna'],
  'Tomato': ['Pusa Ruby', 'Arka Rakshak', 'Pusa Sadabahar', 'Roma', 'Cherry', 'Sioux', 'Heirloom', 'Beefsteak'],
  'Chilli': ['Guntur Sannam', 'Byadgi', 'Kashmiri', 'Jwala', 'Kanthari', 'Mundu', 'Naga Viper', 'Bhut Jolokia (Ghost Pepper)'],
  'Coconut': ['West Coast Tall', 'East Coast Tall', 'Chowghat Orange Dwarf', 'Malayan Yellow Dwarf', 'Tiptur Tall', 'De-ejay'],
  'Banana': ['Robusta', 'Dwarf Cavendish', 'Nendran', 'Poovan', 'Red Banana', 'Grand Naine', 'Yelakki', 'Rasthali'],
  'Brinjal (Eggplant)': ['Pusa Purple Long', 'Arka Navneet', 'Black Beauty', 'Green Long', 'Pusa Kranti', 'Manjari Gota'],
  'Coffee': ['Arabica (Kent, S.795, Cauvery)', 'Robusta (Peradeniya, S.274, CxR)'],
  'Tea': ['Assam', 'Darjeeling', 'Nilgiri', 'Kangra', 'Dooars-Terai'],
  'Cotton': ['MCU-5', 'Suvin', 'DCH-32', 'Bunny', 'Suraj', 'LRA 5166'],
  'Sugarcane': ['Co 86032', 'CoJ 64', 'Co 0238', 'Co 1148', 'Co 671', 'Co 7717'],
  'Areca nut': ['Mangala', 'Sumangala', 'Sreemangala', 'VTL-11', 'VTL-17'],
  'Black Pepper': ['Panniyur-1', 'Karimunda', 'Kuthiravally', 'Panniyur-5', 'Subhakara'],
  'Cardamom': ['Malabar', 'Mysore', 'Vazhukka', 'Njallani', 'Green Gold'],
  'Drumstick (Moringa)': ['PKM-1', 'PKM-2', 'ODC', 'Rohit-1'],
  'Jackfruit': ['Varikka', 'Koozha', 'Singapore', 'Gumless'],
  'Papaya': ['Coorg Honey Dew', 'Pusa Delicious', 'Red Lady', 'Pusa Nanha', 'CO-8'],
  'Rubber': ['RRIM 600', 'GT 1', 'RRII 105', 'RRII 430'],
  'Turmeric': ['Alleppey', 'Erode', 'Salem', 'Rajapuri', 'Prathibha'],
  'Ginger': ['Cochin', 'Calicut', 'Nadia', 'Maran', 'Suprabha'],
  'Wheat': ['Sonalika', 'Kalyan Sona', 'HD 2967', 'WH 1105', 'PBW 343'],
  'Groundnut (Peanut)': ['Kadiri-3', 'TMV-2', 'JL-24', 'TAG-24'],
  'Onion': ['Pusa Red', 'N-53', 'Bellary Red', 'Arka Kalyan'],
  'Potato': ['Kufri Jyoti', 'Kufri Pukhraj', 'Kufri Bahar', 'Chipsona-1'],
  'Mustard': ['Pusa Bold', 'Varuna', 'Kranti'],
  'Sunflower': ['Morden', 'KBSH-1', 'Surya'],
  'Grapes': ['Thompson Seedless', 'Bangalore Blue', 'Anab-e-Shahi', 'Dilkhush'],
  'Pomegranate': ['Ganesh', 'Bhagwa', 'Mridula', 'Arakta'],
  'Guava': ['Allahabad Safeda', 'Sardar (L-49)', 'Arka Mridula', 'Chittidar'],
  'Lentil': ['Pusa Vaibhav', 'WBL 77', 'IPL 316'],
  'Chickpea': ['Pusa 256', 'JG-11', 'KWR 108'],
  'Soybean': ['JS-335', 'JS-93-05', 'Bragg'],
  'Millet (Ragi)': ['GPU-28', 'PR 202', 'Indaf-5']
};
